require("jquery/dist/jquery.min");
require("slider-ui");
require("slider-styles");
require("jquery-ui/ui/i18n/datepicker-ru.js");
require("jquery-ui/themes/base/datepicker.css");
require("css-reset-and-normalize/css/reset-and-normalize.min.css");
import './fonts.scss';
import './layout.scss';
import './blocks/range-slider/range-slider.js';
import './blocks/dropdown/dropdown.js';
import './blocks/data-dropdown/data-dropdown.js';
